name: speed_of_play
description: "SpeedOfPlay awareness & reactivity trainer prototype"
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/RPT-SpeedOfPlay.png

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.2
  wakelock_plus: ^1.2.4
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  intl: 0.20.2
  uuid: ^4.4.0
  just_audio: ^0.10.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icon_ios_1024.png
  adaptive_icon_foreground: assets/icon_foreground_1024.png
  adaptive_icon_background: "#000000"   # or assets/icon_background.png
